#!/usr/bin/env bash
# echos Best School ten times using while loop and conditional statements
i=0
while [ $i -ne 11 ]
do
        if [ $i -eq 9 ]
        then
            echo "Hi"
        else
            echo "Best School"
        fi  
        i=$(( i + 1))
done
